# Generated by Django 5.1.6 on 2026-01-09 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_diabetesprediction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diabetesprediction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='diabetesprediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DocGPTConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeartDiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('chest_pain_type', models.IntegerField(default=0)),
                ('blood_pressure', models.IntegerField(default=120)),
                ('cholesterol', models.IntegerField(default=200)),
                ('fasting_blood_sugar', models.BooleanField(default=False)),
                ('ecg', models.IntegerField(default=0)),
                ('max_heart_rate', models.IntegerField(default=150)),
                ('exercise_angina', models.BooleanField(default=False)),
                ('st_depression', models.FloatField(default=0)),
                ('prediction', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('body_area', models.CharField(default='general', max_length=50)),
                ('severity', models.CharField(default='mild', max_length=20)),
                ('duration', models.CharField(default='hours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
