# Generated by Django 6.0.2 on 2026-02-06 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0003_alter_diabetesprediction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep_hours', models.FloatField(default=0)),
                ('exercise_minutes', models.IntegerField(default=0)),
                ('water_ml', models.IntegerField(default=0)),
                ('food_habit', models.CharField(choices=[('healthy', 'Healthy'), ('mixed', 'Mixed'), ('junk', 'Junk')], default='mixed', max_length=50)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_pressure_sys', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_dia', models.IntegerField(blank=True, null=True)),
                ('mood', models.CharField(default='neutral', max_length=20)),
                ('stress_level', models.IntegerField(default=0)),
                ('health_score', models.IntegerField(default=0)),
                ('suggestions', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
