# Generated by Django 6.0 on 2026-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role_chatmessage_doctorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
